service: super-human

provider:
  name: aws
  runtime: nodejs4.3
  region: us-west-2

functions:
  btn-press:
    cljs: super-human.core/btn-press
    events:
      - http:
          path: btn-press
          method: post

plugins:
  - serverless-cljs-plugin
